/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.dita.options;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

final class DITAConfigurationPanel extends javax.swing.JPanel implements PropertyChangeListener {

    private final DITAConfigurationOptionsPanelController controller;

    DITAConfigurationPanel(DITAConfigurationOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
        controller.addPropertyChangeListener(this);

    }

    public void propertyChange(PropertyChangeEvent evt) {
        System.out.println(evt);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ditaHomeLabel = new javax.swing.JLabel();
        ditaHomeTextField = new javax.swing.JTextField();
        selectDitaHomeButton = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(ditaHomeLabel, org.openide.util.NbBundle.getMessage(DITAConfigurationPanel.class, "DITAConfigurationPanel.ditaHomeLabel.text")); // NOI18N

        ditaHomeTextField.setText(org.openide.util.NbBundle.getMessage(DITAConfigurationPanel.class, "DITAConfigurationPanel.ditaHomeTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(selectDitaHomeButton, org.openide.util.NbBundle.getMessage(DITAConfigurationPanel.class, "DITAConfigurationPanel.selectDitaHomeButton.text")); // NOI18N
        selectDitaHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDitaHomeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ditaHomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ditaHomeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectDitaHomeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ditaHomeLabel)
                    .addComponent(ditaHomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectDitaHomeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectDitaHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDitaHomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectDitaHomeButtonActionPerformed

    void load() {
        File ditaHome = DitaPreferences.getDitaHome();
        if (ditaHome != null) {
            ditaHomeTextField.setText(ditaHome.getAbsolutePath());
        }
    }

    void store() {
        File ditaHome = new File(ditaHomeTextField.getText());
        if (ditaHome.exists()) {
            DitaPreferences.setDitaHome(ditaHome);
        }
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return new File(ditaHomeTextField.getText()).exists();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ditaHomeLabel;
    private javax.swing.JTextField ditaHomeTextField;
    private javax.swing.JButton selectDitaHomeButton;
    // End of variables declaration//GEN-END:variables

    class MyDocListener implements DocumentListener {

        public void insertUpdate(DocumentEvent e) {
            controller.changed();
        }

        public void removeUpdate(DocumentEvent e) {
            controller.changed();
        }

        public void changedUpdate(DocumentEvent e) {
            controller.changed();
        }
    }
}
