/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.netbeans.modules.iconeditor.options;

final class ImageEditorPanel extends javax.swing.JPanel {

    private final ImageEditorOptionsPanelController controller;

    ImageEditorPanel(ImageEditorOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        svgEditorLabel = new javax.swing.JLabel();
        svgEditorTextField = new javax.swing.JTextField();
        otherEditorLabel = new javax.swing.JLabel();
        otherEditorTextField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(svgEditorLabel, org.openide.util.NbBundle.getMessage(ImageEditorPanel.class, "ImageEditorPanel.svgEditorLabel.text")); // NOI18N

        svgEditorTextField.setText(org.openide.util.NbBundle.getMessage(ImageEditorPanel.class, "ImageEditorPanel.svgEditorTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(otherEditorLabel, org.openide.util.NbBundle.getMessage(ImageEditorPanel.class, "ImageEditorPanel.otherEditorLabel.text")); // NOI18N

        otherEditorTextField.setText(org.openide.util.NbBundle.getMessage(ImageEditorPanel.class, "ImageEditorPanel.otherEditorTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherEditorLabel)
                    .addComponent(svgEditorLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(svgEditorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(otherEditorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svgEditorLabel)
                    .addComponent(svgEditorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otherEditorLabel)
                    .addComponent(otherEditorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        String svgEditor = ImageEditorPreferences.getSvgEditor();
        if (svgEditor != null) {
            svgEditorTextField.setText(svgEditor);
        }
        String otherEditor = ImageEditorPreferences.getOtherEditor();
        if (otherEditor != null) {
            otherEditorTextField.setText(otherEditor);
        }
    }

    void store() {
        ImageEditorPreferences.setSvgEditor(svgEditorTextField.getText());
        ImageEditorPreferences.setOtherEditor(otherEditorTextField.getText());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel otherEditorLabel;
    private javax.swing.JTextField otherEditorTextField;
    private javax.swing.JLabel svgEditorLabel;
    private javax.swing.JTextField svgEditorTextField;
    // End of variables declaration//GEN-END:variables
}
